### ISSUE TITLE
Small artifacts in hd bg's apha channel upon import(room 9)

### ISSUE THREAD

**Issue by pepper-jelly** [stoofin/roomviewer-rde#1]
Only layer 0 enabled. On right side I just added a little brightness. It looks like additional tiles are drawing on top in multiply mode and add transparency when pixels exceed some value.
![Scr](https://user-images.githubusercontent.com/45047877/164612562-e25a0c7c-15c8-4866-86d3-1f5846a42f62.png)

Try to import these 2 layers to reproduce issue.

alu_a10i-layer0-op.png
![alu_a10i-layer0-op](https://user-images.githubusercontent.com/45047877/164614031-eaabbd3e-1bed-4852-9d33-38a973520515.png)

alu_a10i-layer1-op.png
![alu_a10i-layer1-op](https://user-images.githubusercontent.com/45047877/164617615-babda586-b39a-43f6-a58d-5b4b01908f5a.png)

**Comment by stoofin** [comment]
Hey. I'm _pretty sure_ that this is caused by the underlying tile being reused across layers.  So what I think is happening is that the tile being contributed by layer1 has that corner transparent, and on import that version is taking precedence just because the program happens to load it second.  So the artifact is a transparent hole through to the black background.  And the effect you're seeing with the 1% brightness bump is where the layer1 tiles (which haven't been brightened) are overwriting layer0's.

Here's what happens to layer0 if I import it alongside a completely green layer1:
![Screenshot_20220422_211311](https://user-images.githubusercontent.com/44447892/164874810-de2642c2-a13b-492e-8a4d-406cc254c6f0.png)

So it sure looks like tile reuse (the kind which is unfortunately baked into the psx data) and if that's the case, there are a few fixes we could try:
- manually fixing the holes (tedious)
- a new version that loads the layers in reverse, so a hopefully fully opaque tile is preferred
- a new version that keeps all opaque pixels it sees instead of replacing tiles wholesale
- a visualizer for which tiles are reused?

Alternatively. if someone gets texture replacement working at the d3d11 level. the .chip2 format could be bypassed entirely and tile shenanigans wouldn't matter.

**Comment by pepper-jelly** [comment]
Thanks for explanation. Actually reverse load seem best if will work.
I've been using imagemagick to copy upscaled bg image to other layers.
So far I didn't notice the issue after extending alpha in my script.
``` bash
convert fg.png -resize 400% -channel A -blur 0x5 -level 45% -morphology Dilate Disk:2 fg.png
convert -composite -compose Dst_In bg.png fg.png -alpha Set fg.png
```

**Comment by stoofin** [comment]
Okay, I uploaded a new version that imports in reverse order to the releases page.

**Comment by pepper-jelly** [comment]
@stoofin I just tested it. It seems now comply with psx data because room's 0 bg should take lead and in room 1 layer with curtain in sunlight is above and loaded before bg. Issue solved. I will add you to credits when finish it and post on nexusmod or somewhere.
![Scr 24 Apr 04:28:15](https://user-images.githubusercontent.com/45047877/164951903-d89bcac4-e4df-4fad-bb02-b808b75e5caa.jpg)
